// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfr4mIpRT_uTH_77ieGNnlNHUFYP81rhE',
    appId: '1:695224188894:web:4ed98c311d60144088e74f',
    messagingSenderId: '695224188894',
    projectId: 'car-workshop-d07d8',
    authDomain: 'car-workshop-d07d8.firebaseapp.com',
    storageBucket: 'car-workshop-d07d8.appspot.com',
    measurementId: 'G-1FHM6P82WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgWzRQCvV37dgwWJSE4ofobb2lOzSsavM',
    appId: '1:695224188894:android:752f946af576021d88e74f',
    messagingSenderId: '695224188894',
    projectId: 'car-workshop-d07d8',
    storageBucket: 'car-workshop-d07d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJTbGJfQyvZ8vpG4Sg-V4pJ5YvfaZwbhE',
    appId: '1:695224188894:ios:3af90fa8db359f4688e74f',
    messagingSenderId: '695224188894',
    projectId: 'car-workshop-d07d8',
    storageBucket: 'car-workshop-d07d8.appspot.com',
    iosBundleId: 'com.example.carWorkshop',
  );

}